### ISSUE TITLE
Different minimap2 alignment results of different FunAnnotate version

### ISSUE THREAD

**Issue by qihualiang** [nextgenusfs/funannotate#444]
When I used FunAnnotate v1.7.2, I was able to align transcripts to genome with minimap2, log as 
`[06/22/20 12:34:13]: Aligning transcript evidence to genome with minimap2
[06/22/20 12:34:13]: /home/qliang/0.soft/miniconda2/envs/funannotate/lib/python2.7/site-packages/funannotate/aux_scripts/sam2bam.sh minimap2 -ax splice -t 36 --cs -u b -G 3000 /home/qliang/results_minimap/predict_misc/genome.softmasked.fa results_minimap/predict_misc/transcripts.combined.fa 4 results_minimap/predict_misc/transcripts.minimap2.bam
[06/22/20 12:34:18]: [M::mm_idx_gen::0.426*1.00] collected minimizers
[M::mm_idx_gen::0.496*2.30] sorted minimizers
[M::main::0.496*2.30] loaded/built the index for 21 target sequence(s)
[M::mm_mapopt_update::0.540*2.19] mid_occ = 160
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 21
[M::mm_idx_stat::0.572*2.12] distinct minimizers: 2337210 (92.46% are singletons); average occurrences: 1.407; average spacing: 2.929
[M::worker_pipeline::4.270*19.98] mapped 30940 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 36 --cs -u b -G 3000 /home/qliang/results_minimap/predict_misc/genome.softmasked.fa results_minimap/predict_misc/transcripts.combined.fa
[M::main] Real time: 4.290 sec; CPU: 85.338 sec; Peak RSS: 0.511 GB
[bam_sort_core] merging from 0 files and 4 in-memory blocks...

[06/22/20 12:34:25]: Found 20,273 alignments, wrote GFF3 and Augustus hints to file`

I updated FunAnnotate to v1.8.0 and repeated with same files/settings, but transcripts alignments were different with 0 alignments. Log as 
`
[06/29/20 12:21:03]: Aligning transcript evidence to genome with minimap2
[06/29/20 12:21:03]: minimap2 -ax splice -t 36 --cs -u b -G 3000 /home/qliang/results_minimap/predict_misc/genome.softmasked.fa results_minimap/predict_misc/transcripts.combined.fa | samtools sort --reference /home/qliang/results_minimap/predict_misc/genome.softmasked.fa -@ 4 -o results_minimap/predict_misc/transcripts.minimap2.bam -
[06/29/20 12:22:00]: Found 0 alignments, wrote GFF3 and Augustus hints to file
`

I ran the cmd in log 
`minimap2 -ax splice -t 36 --cs -u b -G 3000 /home/qliang/results_minimap/predict_misc/genome.softmasked.fa results_minimap/predict_misc/transcripts.combined.fa | samtools sort --reference /home/qliang/results_minimap/predict_misc/genome.softmasked.fa -@ 4 -o results_minimap/predict_misc/transcripts.minimap2.bam -`
The output was
`[M::mm_idx_gen::0.414*1.00] collected minimizers
[M::mm_idx_gen::0.480*2.30] sorted minimizers
[M::main::0.480*2.30] loaded/built the index for 21 target sequence(s)
[M::mm_mapopt_update::0.520*2.20] mid_occ = 160
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 21
[M::mm_idx_stat::0.548*2.14] distinct minimizers: 2337210 (92.46% are singletons); average occurrences: 1.407; average spacing: 2.929
[M::worker_pipeline::3.805*22.79] mapped 30940 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 36 --cs -u b -G 3000 /home/qliang/results_minimap/predict_misc/genome.softmasked.fa results_minimap/predict_misc/transcripts.combined.fa
[M::main] Real time: 3.828 sec; CPU: 86.715 sec; Peak RSS: 0.573 GB
[bam_sort_core] merging from 0 files and 4 in-memory blocks...`

It seems like there is no explicit error of running minimap2, but it is weird that there is no alignment at all for transcripts2genome. Could you help troubleshooting this? Many thanks!

**Comment by nextgenusfs** [comment]
Thanks for reporting -- likely a bug in the master code.  I added the `--reference` to samtools sort to accommodate another bug from a user with a large genome, that must be the error I'm assuming.  Is the BAM file empty?

**Comment by qihualiang** [comment]
The BAM file is not empty, but I notice the file size of this file increase by 1byte compared to my previous run of v1.7.2

**Comment by nextgenusfs** [comment]
okay, so `samtools view results_minimap/predict_misc/transcripts.minimap2.bam | wc -l` yields how many alignments compared to the v1.7.2?

**Comment by nextgenusfs** [comment]
And if you wouldn't mind checking the header for both of them? `samtools view -H file.bam`, maybe that is where discrepancy is?

**Comment by qihualiang** [comment]
BAM from v1.8.0 has 36947 lines; from v1.7.2 has 37492 lines
They have the exact same header

**Comment by nextgenusfs** [comment]
Okay -- that means its not there, its in the processing of the bam to gff3 (alignments).  Its likely then a python2/3 issue -- which version of python?

**Comment by qihualiang** [comment]
Python 2.7

**Comment by nextgenusfs** [comment]
Hmm, okay.  Well when I test it locally I'm not seeing a problem.  You can test the bam2gff3 conversion in the utility menu, ie.
```
funannotate util bam2gff3 -i results_minimap/predict_misc/transcripts.minimap2.bam -o test.gff3
```
I guess I didn't ask if the `predict_misc/transcript_alignments.gff3` file is indeed empty?

**Comment by qihualiang** [comment]
`predict_misc/transcript_alignments.gff3` and `predict_misc/transcript_minimap2.gff3` are empty. 

bam2gff3 could generate non-empty gff3 results

**Comment by nextgenusfs** [comment]
So if the `bam2gff3` is working then I don't know what the problem is.  I would try to re-run perhaps in a clean output folder and see if you get the same behavior.

**Comment by lyl8086** [comment]
Hi, I have the same issue. After checking the codes in `library.py`, I found some potential bugs in function `bam2ExonsHints`.
line 1635:  should be `tags = cols[11:]` ?
line 1664:  should be `cols[1] == '0'` ?
line 1672:  should be `cols[1] == '16'` ?

I'm not sure if I fixed it correctly , but it works for me.

**Comment by nextgenusfs** [comment]
@lyl8086 thanks -- I think you are right, those look like leftover errors from using pybam which is now just samtools for compatibility.

**Comment by nextgenusfs** [comment]
Please reopen if after installing master branch and it is still a problem.
