### ISSUE TITLE
Issue with funannotate update

### ISSUE THREAD

**Issue by viktor-hub** [nextgenusfs/funannotate#453]
When I run `funannotate update -i GCA_000091205.1_ASM9120v1_genomic.gbff -l 1.1.fastq -r 1.2.fastq --out /home/user/fun1 --stranded RF --memory 20G --cpus 4`

I encounter the following issue:
```
[12:05 AM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[12:05 AM]: Running 1.7.4
[12:05 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1765, in main
    GBK, gffout, trnaout, fastaout, spliceout, exonout, proteinsout)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 150, in gbk2pasaNEW
    num_exons = len(v['mRNA'][i])
IndexError: list index out of range
```
I have no idea on how to fix this issue or how to proceed. I'm trying to improve the existing NCBI annotation using RNA-Seq data. I would very much appreciate any assistance regarding this matter. Thank you!

**Comment by nextgenusfs** [comment]
Looks like it encountered some features in the genbank file that it didn’t parse/understand. Looks like it’s a fairly old submission, likely formatting is different than it’s expecting. So we need to figure out why in order to fix the parser. Can you post a few gene models from the GBK file and maybe I can see the problem. Otherwise you can try to get the fasta and GFF3 files from NCBI and try to feed those to funannotate update.

**Comment by viktor-hub** [comment]
The NCBI files I'm using were obtained from [here](https://ftp.ncbi.nlm.nih.gov/genomes/genbank/plant/Cyanidioschyzon_merolae/latest_assembly_versions/GCA_000091205.1_ASM9120v1/).

These are some excerpts from the `GCA_000091205.1_ASM9120v1_genomic.gbff` file I was trying to use:
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
LOCUS       AP006485              481791 bp    DNA     linear   PLN 19-MAR-2019
DEFINITION  Cyanidioschyzon merolae strain 10D DNA, chromosome 3, complete
            genome.
ACCESSION   AP006485
VERSION     AP006485.2
DBLINK      BioProject: PRJNA10792
KEYWORDS    .
SOURCE      Cyanidioschyzon merolae strain 10D
  ORGANISM  Cyanidioschyzon merolae strain 10D
            Eukaryota; Rhodophyta; Bangiophyceae; Cyanidiales; Cyanidiaceae;
            Cyanidioschyzon.
REFERENCE   1
  AUTHORS   Matsuzaki,M., Misumi,O., Shin-I,T., Maruyama,S., Takahara,M.,
            Miyagishima,S.Y., Mori,T., Nishida,K., Yagisawa,F., Nishida,K.,
            Yoshida,Y., Nishimura,Y., Nakao,S., Kobayashi,T., Momoyama,Y.,
            Higashiyama,T., Minoda,A., Sano,M., Nomoto,H., Oishi,K.,
            Hayashi,H., Ohta,F., Nishizaka,S., Haga,S., Miura,S., Morishita,T.,
            Kabeya,Y., Terasawa,K., Suzuki,Y., Ishii,Y., Asakawa,S., Takano,H.,
            Ohta,N., Kuroiwa,H., Tanaka,K., Shimizu,N., Sugano,S., Sato,N.,
            Nozaki,H., Ogasawara,N., Kohara,Y. and Kuroiwa,T.
  TITLE     Genome sequence of the ultrasmall unicellular red alga
            Cyanidioschyzon merolae 10D
  JOURNAL   Nature 428 (6983), 653-657 (2004)
   PUBMED   15071595
REFERENCE   2
  AUTHORS   Nozaki,H., Takano,H., Misumi,O., Terasawa,K., Matsuzaki,M.,
            Maruyama,S., Nishida,K., Yagisawa,F., Yoshida,Y., Fujiwara,T.,
            Takio,S., Tamura,K., Chung,S.J., Nakamura,S., Kuroiwa,H.,
            Tanaka,K., Sato,N. and Kuroiwa,T.
  TITLE     A 100%-complete sequence reveals unusually simple genomic features
            in the hot-spring red alga Cyanidioschyzon merolae
  JOURNAL   BMC Biol. 5, 28 (2007)
   PUBMED   17623057
  REMARK    Publication Status: Online-Only
REFERENCE   3  (bases 1 to 481791)
  AUTHORS   Kohara,Y., Shin-i,T., Matsuzaki,M., Misumi,O., Ogasawara,N. and
            Kuroiwa,T.
  TITLE     Direct Submission
  JOURNAL   Submitted (21-JUN-2003) Contact:Motomichi Matsuzaki RIKEN Center
            for Advanced Intelligence Project; 1-4-1 Nihonbashi, Chuo-ku, Tokyo
            103-0027, Japan
COMMENT     On Jul 11, 2007 this sequence version replaced AP006485.1.
FEATURES             Location/Qualifiers
     source          1..481791
                     /organism="Cyanidioschyzon merolae strain 10D"
                     /mol_type="genomic DNA"
                     /strain="10D"
                     /db_xref="taxon:280699"
                     /chromosome="3"
     misc_feature    878..3373
                     /note="repetitive element"
     gene            complement(4016..6349)
                     /locus_tag="CYME_CMC002C"
     CDS             complement(4016..6349)
                     /locus_tag="CYME_CMC002C"
                     /codon_start=1
                     /product="similar to hedgehog protein"
                     /protein_id="BAM78955.1"
                     /translation="MKGGLRRSSLRRVLWLRVLVVCLWFSARIWVLVGAGAPAYPVRW
                     TWIGGETSVNNYGKYGTLNVASSNNVPGGRHYSSTWVGSPGVLYLFGGFGYANSSGGY
                     LNDLWRLNVTSLEWAWIGGSMDIYVPGNYGTLGVGSALNIPGAREASAFWRADEEHFW
                     LFGGYGLDGNGNIGCLNDMWQYDTVSGNWTWVDGNDTINALPTYGPMGSYDPSYNPGA
                     RLKAAFWLGADGNFWLFGGENCYSYLFSDLWCFNRSLSLWAYMGGSQSVNQPGNYSEP
                     DIANRSNAPGARQGAITWTDSKANLWMFGGFGYGNGSESYPGFLNDLWFYNISTSIWT
                     FVAGNTTISIPGSYIIFGNTDAASYPGSREYGVGFIDASGNLQLFGGEGYGNSSSESG
                     DLNDLWLFNVEQRQWAWINGSAVINAPADYGMFRTFSPSVVPGARYGSALWNTTESGM
                     ILFGGFGYSNTSEGKGELNDIFMLSESMITPSPTPTPTPTPTPTPTPTPTPTSTSTPT
                     ATPTASATPSLSATPSTAANVTKIPINGGTTICFPEDATVLIDRLGSIRPMSELRSGM
                     SVIGADRSGQLLEDTILGWLHKEPGATAEVLLIKTLSGKQLRLTSQHLVYRMHASMRV
                     RDFGMTPFSDLLRHQQTIHQRPELESLALEAVFAEHIRIGDALLDAAAHRADPVVAID
                     TYVTREGVYAPLTRSGRLVVDGLLVSCYGTYASQEVAHAVLWPARVDVLRTMCGSALG
                     SDSTASIMPYAERLYRIYASAAQILEKARVIVIGAAC"
     misc_feature    6927..9687
                     /note="repetitive element"
     gene            complement(10701..12402)
                     /locus_tag="CYME_CMC004Z"
     misc_feature    complement(10701..12402)
                     /locus_tag="CYME_CMC004Z"
                     /note="pseudo-gene of hedgehog protein"
     gene            complement(13335..15206)
                     /locus_tag="CYME_CMC005C"
     CDS             complement(13335..15206)
                     /locus_tag="CYME_CMC005C"
                     /codon_start=1
                     /product="similar to trefoil factor"
                     /protein_id="BAM78956.1"
                     /translation="MRPGAGKYRNFGELCKQLFVLVAALSLAVGCATLGAEAQSTMTA
                     TATLSPTSSVAPSVSATMTPTPTMTPTPTPTMTPTTTTSPTIVPTTISTSIAISVQNL
                     SLCLAVATDLQNDLEARFIGLEVNVSVTDNCDTVFGSGTSRRLATTLDKSNPRLERAL
                     VRTSGGSVVTYVIKISGDTSLASELQIVLQTFTDLLSTILPSGATLAIITPTPSATPT
                     PVCTSEICGSPGQYTNQDACEQVGCCFNAQTNACTLKSVSAACSAVPVTQRVPCGWSY
                     IYPDECTAIPGCCWQPTANGILAPWCYYDINHAPQASVALQEVQAPVPLCPSPGAQRQ
                     PCGNAGINQFTCYAQGCCYDSQAQNQWVQNGKQQSDFESNPYCFQPVKTCAVGEFERQ
                     PCTNAVNQNQQLNNNINNNQFVRLLNTLLYGEQHGTQRTSYSPQQCLEAGCCLGLSNE
                     CFQPMTEYVCQTYGYVSNSLSGTTGNVSNSSYIPCGPECCNAETQNCTYNPFSNNNNQ
                     QQQQQLQQQQQQQVLLPSFCVCKDPTKQCGTYLIPSDNLVNKVRCCRADEECINNQCV
                     VISPTPTPSPVAVTATPSATVSATVSATASATASVSVSASASVSASVSTSASAFSTV"
     gene            13666..16610
                     /locus_tag="CYME_CMC006T"
     misc_RNA        13666..16610
                     /locus_tag="CYME_CMC006T"
                     /product="hypothetical transcript"
     misc_feature    15865..18135
                     /note="repetitive element"
     gene            18425..18847
                     /locus_tag="CYME_CMC008C"
     CDS             18425..18847
                     /locus_tag="CYME_CMC008C"
                     /codon_start=1
                     /product="NADH dehydrogenase I alpha subcomplex 7"
                     /protein_id="BAM78957.1"
                     /translation="MTTYAENLVSTWTSVAPIVVEAANLAAVPRNSRADQCAIAQVVA
                     KDTELTTEAGAPNRYNTRSQKPALIPQGPPQRIFDITYHTRDDRRRVFRETYLLRVAP
                     SEPIANPTTGEDASPLPPLPGRNLQWQPLGTLKDYTRE"
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
     gene            122628..123195
                     /locus_tag="CYME_CMC053C"
     CDS             join(122628..122764,122934..123195)
                     /locus_tag="CYME_CMC053C"
                     /codon_start=1
                     /product="60S ribosomal protein L35"
                     /protein_id="BAM78995.1"
                     /translation="MVLKAHELRGKSRQELEQQLQALKTELQQLRVLQVSGGGAGKLG
                     KIKEVRKSIARVLTVMSQARRKALREEYMNKKFKPLDLRPKLTRAMRRKLSKTDAARK
                     TLRQQKREQNFPKRRFAILPVPRDSLMQSE"
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
ORIGIN      
        1 ccccccattc cccccattta cctccaaccc acgcacttca cgcacttccc cattaacgcg
       61 atgatcccag tgccaatgca tatgtgatta tgacttctat ctctcaaaat tcattactga
      121 tccgtcttcg gcggtacgat ctgagcgcgt acgcatctgt tatatctcca tctggcattc
      181 catgatcatt actgttttac ctccagcttt tttgtttttg gttttgacag aacctctaca
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

When I try `funannotate update --fasta GCA_000091205.1_ASM9120v1_genomic.fna --gff GCA_000091205.1_ASM9120v1_genomic.gff -l 1.1.fastq -r 1.2.fastq --out /home/user/fun2 --stranded RF --memory 20G --cpus 4`, 
I get the following error:
`Error, can't find ID or Parent. Malformed GFF file.`
`AP006483.2	DDBJ	region	1	422616	.	+	.	ID=AP006483.2:1..422616;Dbxref=taxon:280699;Name=1;chromosome=1;gbkey=Src;mol_type=genomic DNA;strain=10D`

Thank you so very much for looking into this!

**Comment by nextgenusfs** [comment]
The GBK fix will take more time, I think I just pushed a fix that hopefully will help with the GFF3/FASTA parsing. If you installed with Conda you can pull the latest version and install from that environment with pip, ie
```
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```

Let me know if that solves it.

**Comment by nextgenusfs** [comment]
I think the problem with the GBK file is associated with there are apparently no mRNA features and/or there are genes followed by this 'misc_RNA' feature, which the parser doesn't know what to do with.  I think its probably the latter causing the problem, I'll see if it works to just ignore those features.  But this is maybe the problem:
```
     gene            13666..16610
                     /locus_tag="CYME_CMC006T"
     misc_RNA        13666..16610
                     /locus_tag="CYME_CMC006T"
                     /product="hypothetical transcript"
     misc_feature    15865..18135
                     /note="repetitive element"
```

Whereas what a proper eukaryotic GBK file should have gene, mRNA, and CDS:
```
LOCUS       scaffold_27           427039 bp    DNA     linear       25-JUN-2020
DEFINITION  Genome one.
ACCESSION   
VERSION
KEYWORDS    .
SOURCE      Genome one
  ORGANISM  Genome one
            Unclassified.
REFERENCE   1  (bases 1 to 427039)
  AUTHORS   Palmer,J.M.
  TITLE     Direct Submission
  JOURNAL   Submitted (25-JUN-2020) CFMR, USDA Forest Service, 1 Gifford
            Pinchot Drive, Madison, WI 53726, USA
COMMENT     'Annotated using 1.8.0'.
FEATURES             Location/Qualifiers
     source          1..427039
                     /organism="Genome one"
                     /mol_type="genomic DNA"
     gene            complement(3511..4544)
                     /locus_tag="BIGTIME_000002"
     mRNA            complement(join(3511..3756,3816..4544))
                     /locus_tag="BIGTIME_000002"
                     /product="hypothetical protein"
     CDS             complement(join(3511..3756,3816..4544))
                     /locus_tag="BIGTIME_000002"
                     /note="EggNog:ENOG410Q4GS;
                     GO_function: GO:0016491 - oxidoreductase activity
                     [Evidence IEA];
                     GO_process: GO:0055114 - oxidation-reduction process
                     [Evidence IEA]"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:BIGTIME_000002-T1"
                     /db_xref="InterPro:IPR005123"
                     /translation="MPPVPSIQKRHQHHTAHSPYEWKERREFSHNWKAKFRGNARVIT
                     TDLAWTNLITPANPKVTTTLEQGLELSKHLTLLQGIPKDGGKDGLDIQPVTVFNSADK
                     DPEQLLVYMRGRLSLPDRNKDLCRLMAGAIEQYTELAPPPKPSSDKRHEMEQARKAER
                     EGKKWGVYHLGLWHATGQTNSPPTICSDMRRTGNGFGATLALYKKMAPLAQTIGRLFQ
                     EIDPRAYEQYRQNYLRECAATPELEVGPHKDNHDVLDGWVAMACFGEFEGGELCLPAL
                     GYKIPFQPGDVVLFRSAVLEHWIAPFEGTRYSCVFFTKQSNWQPGEEE"
     gene            complement(6311..10771)
                     /locus_tag="BIGTIME_000005"
     mRNA            complement(join(6311..6563,6594..10771))
                     /locus_tag="BIGTIME_000005"
                     /product="hypothetical protein"
     CDS             complement(join(6311..6563,6594..10771))
                     /locus_tag="BIGTIME_000005"
                     /note="EggNog:ENOG410PKKD;
                     COG:S;
                     GO_function: GO:0005524 - ATP binding [Evidence IEA];
                     GO_function: GO:0003676 - nucleic acid binding [Evidence
                     IEA]"
                     /codon_start=1
                     /product="hypothetical protein"
                     /protein_id="ncbi:BIGTIME_000005-T1"
                     /db_xref="InterPro:IPR001650"
                     /db_xref="InterPro:IPR011545"
                     /db_xref="InterPro:IPR014001"
                     /db_xref="InterPro:IPR022698"
                     /db_xref="InterPro:IPR027417"
                     /db_xref="PFAM:PF00270"
                     /db_xref="PFAM:PF00271"
                     /db_xref="PFAM:PF12013"
                     /translation="MAASFSYLATHGVLLCRDCGTCLMPARASQEWHLRHPPHDLKGP
                     ELRTLLDLFATHELRPPGQVALPDQPCIAIEGLRRHPAFSCILCDDGRPTLTRSGPAI
                     RAHVSREHGQKPSQQSEGGAWQRCTVQTFFAKTEHVRYFVVTDDDRAEGDAATAAIAL
                     EPQEQAFFDLADADATMVADDIKTEGNKVHGFDSHPSAAVPWLRRTGIENHVRGLEKD
                     EMHASFALPKSADEGEPELFLMLEVMDEILAEVHGWCFDGPDCMLTWPRQLALSRFHG
                     APTSSAPASCRAGRVRGFDPKKEPSTLRTNFGYWKQFMAYCYRVAYCGSHFTPPLSAD
                     QGRRPEDRIRLTDEQTTAWEAALECAADGDRLALNDALRSLCMALVCHEFGGDRFSSP
                     LLSFCAMLSVKPRTKSWKEPGNFNSCLSGLIWAVQLLIFSTAAYLERSGAGSTLEHIN
                     SICEQYLRPDTETPMGEILGWRLLLFAVSKDGVGSHQAHWDEDEQILTYRDVDLNMDE
                     VQQLLLSEFRQAQHLLHGELMFGAAGLPRMRAWALKDNLDADNFSWHFGEHRENAALL
                     KPLAGSLRNVIRESQSLRASFLDTTAAPTAEDGEDGEADAGVMRVMWRQKAIDQYEAV
                     TDEFLKRLLVLIHMASGQPLRESELFSLTWRNTQRRRSVYLKHGLVMLHTTYHKGQQQ
                     TGRFKNNIRFLPAAIGDLLLDYLVYVVPLRQAFLRQSSPRAIMSAYLWWKDGAVWADN
                     RLTRCMEQACVRAKVPRLHIANWRQMTVNIVKTKFAGDLACFEGIGADDDDEDAEEME
                     DDIRTMTRQRNHSTRVVNRSYANQLNANFGNVWDGLIRRNLRASSLWRGLWDLDTVLG
                     DAVAAAGKRKREAAEVAGSDRPRMLKRIAVGVHRPRKRWSAAALLKCARGLYHDDKLQ
                     WKSAAQERAMTVVMSWTEQVVVILGTGEGKSLLFMLPCVLPDAGVTILVLPLVSLRGD
                     LLRRVQELGIDHLVWAPGEERDAPLVFVTVEAASTSQFRAYAHRLAATQQLGRVVIDE
                     AHLTITASEYRHAMADLALIRSVRTQFVYLTATLPPMLQAAFERQNNLVKPKVVRAST
                     NRRNLSYLVQRATGQGSLLEEGARRARDAWRASGLLDQTRDKIILYVRTREEAQDLGS
                     LLRCPVYTAMAGTAEEKQELLRTWLTTPELPYIVATSALSAGFDYPHVRLVMHLDEPR
                     SLVDFAQESGRAGRDGREAYSAVLLPHKWQLQAGNAGMDVETRALYRYLEGRECRRTC
                     LSVHLDEASELRQCDGTRDDVACDVCSSGPSPSHVPRDDATEAMPHTGSAAIHEKRRL
                     AYLELSRYKEDLLTVKGTCLLCRGLREQWDHQFTKCHQRFDFFRARDQARRRGQGRGP
                     WISAFAACYWCYNPHGLEQCRYADIVMPLCYGVFHKTGGEQWLQERFGEQAVRAGAAG
                     AFNDVDVFLSWCGQVAEFAGGKGIWGVKIAAAALLEFEAY"
```

**Comment by nextgenusfs** [comment]
Okay, I think I might have fixed the GBK parsing as well -- install the latest in master to give both the GBK and the GFF+FASTA a try. Would be great if you could confirm if one/both ways are now working.  Thanks.

**Comment by viktor-hub** [comment]
When I tested the initial fix using the NCBI FASTA and GFF files:
```
[01:20 AM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[01:20 AM]: Running 1.8.0
[01:20 AM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[01:20 AM]: Previous annotation consists of: 0 protein coding gene models and 49 non-coding gene models
[01:20 AM]: Adapter and Quality trimming PE reads with Trimmomatic
[01:28 AM]: Running read normalization with Trinity
[01:39 AM]: Building Hisat2 genome index
[01:39 AM]: Aligning reads to genome using Hisat2
[01:40 AM]: Running genome-guided Trinity, logfile: fastaplusgfftrial1/update_misc/Trinity-gg.log
[01:40 AM]: Clustering of reads from BAM and preparing assembly commands
[01:46 AM]: Assembling 7,169 Trinity clusters using 3 CPUs
[03:11 AM]: 10,342 transcripts derived from Trinity
[03:11 AM]: StringTie installed, running StringTie on Hisat2 coordsorted BAM
[03:11 AM]: Converting transcript alignments to GFF3 format
[03:12 AM]: Converting Trinity transcript alignments to GFF3 format
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2161, in main
    aligners=args.aligners)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 584, in runPASA
    line = line.replace('<__DATABASE__>', pasaDBname_path)
NameError: global name 'pasaDBname_path' is not defined
```

Running the same NCBI FASTA and GFF files using your subsequent fix (it appears that it's handling the miscellaneous RNAs now, but it's still missing all of the several thousand protein coding genes):
```
[03:14 PM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[03:14 PM]: Running 1.8.0
[03:14 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[03:14 PM]: Previous annotation consists of: 0 protein coding gene models and 570 non-coding gene models
[03:14 PM]: Adapter and Quality trimming PE reads with Trimmomatic
[03:22 PM]: Running read normalization with Trinity
[03:41 PM]: Building Hisat2 genome index
[03:41 PM]: Aligning reads to genome using Hisat2
[03:43 PM]: Running genome-guided Trinity, logfile: fastaplusgfftrial2/update_misc/Trinity-gg.log
[03:43 PM]: Clustering of reads from BAM and preparing assembly commands
[03:50 PM]: Assembling 7,174 Trinity clusters using 3 CPUs
[07:02 PM]: 10,271 transcripts derived from Trinity
[07:02 PM]: StringTie installed, running StringTie on Hisat2 coordsorted BAM
[07:02 PM]: Converting transcript alignments to GFF3 format
[07:03 PM]: Converting Trinity transcript alignments to GFF3 format
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2161, in main
    aligners=args.aligners)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 584, in runPASA
    line = line.replace('<__DATABASE__>', pasaDBname_path)
NameError: global name 'pasaDBname_path' is not defined
```

Employing the fixes did get everything much further along than before, but I don't know if `NameError: global name 'pasaDBname_path' is not defined` is an unrelated issue or a downstream effect caused by the GFF file issue.

Using the NCBI GBK file in conjunction with the subsequent fix (result is the same as before):
```
[07:29 PM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[07:29 PM]: Running 1.8.0
[07:29 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1819, in main
    GBK, gffout, trnaout, fastaout, spliceout, exonout, proteinsout)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 150, in gbk2pasaNEW
    num_exons = len(v['mRNA'][i])
IndexError: list index out of range
```


Thank you for all of the time you're spending on this - I really appreciate it.

**Comment by nextgenusfs** [comment]
Thanks for the update -- sorry I must not have gotten it completely correct. The error about pasaDBname_path is actually a typo -- so I fixed that. Trying to understand why the genes/mRNA features aren't coming through. They appear to be working for me with these GFF + FASTA files.  Can you try to run again making sure you are specifying a new output directory? Its possible if you used same command that it would re-use some existing data. 

But I did just push a fix for the pasa database name (hopefully), so install master again from pip and then run in a clean output directory with the GFF+FASTA -- hopefully that works.  I will try to address the GBK now.

This annotation seems odd to me -- out of ~ 4800 protein coding genes, there are only 26 that have multiple exons?  I guess that's plausible, but would be strange.  I would also try to run funannotate from scratch with these genome and see if you get similar numbers, ie you can follow the train --> predict --> update methodology.

**Comment by nextgenusfs** [comment]
And I used the RefSeq GFF and FNA files from here: https://www.ncbi.nlm.nih.gov/assembly/GCF_000091205.1/

**Comment by viktor-hub** [comment]
After installing the master again from pip and using a clean output directory, as well as the RefSeq GFF and FNA files you used, it looks like everything is being imported correctly.  One of the interesting things about this organism is that it actually has an unusually low number of introns.  Unfortunately, there's a different error that I'm encountering now:

```
[04:18 PM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[04:18 PM]: Running 1.8.0
[04:18 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[04:18 PM]: Previous annotation consists of: 4,803 protein coding gene models and 570 non-coding gene models
[04:18 PM]: Adapter and Quality trimming PE reads with Trimmomatic
[04:25 PM]: Running read normalization with Trinity
[04:36 PM]: Building Hisat2 genome index
[04:36 PM]: Aligning reads to genome using Hisat2
[04:37 PM]: Running genome-guided Trinity, logfile: GCFtrial/update_misc/Trinity-gg.log
[04:37 PM]: Clustering of reads from BAM and preparing assembly commands
[04:44 PM]: Assembling 7,154 Trinity clusters using 3 CPUs
[06:10 PM]: 10,314 transcripts derived from Trinity
[06:10 PM]: StringTie installed, running StringTie on Hisat2 coordsorted BAM
[06:10 PM]: Converting transcript alignments to GFF3 format
[06:11 PM]: Converting Trinity transcript alignments to GFF3 format
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2161, in main
    aligners=args.aligners)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 590, in runPASA
    line = line.replace('<__MIN_PERCENT_ALIGNED__>', min_pct_aligned)
TypeError: expected a string or other character buffer object
```

Thanks!

**Comment by nextgenusfs** [comment]
Uggh.. Sorry.  I appreciate you testing this though -- the code base has undergone a large change to support python 3.....  you can give it a try again, you can avoid the dependencies and make sure it installs current with:
```
python -m pip installl --no-deps --force git+https://github.com/nextgenusfs/funannotate.git
```
Hopefully that works, just needed to be a string instead of integer..... Not sure why I haven't gotten that error locally....

**Comment by viktor-hub** [comment]
After updating, I used the same input files as the previous round, and a fresh output directory just in case:
```
[11:19 PM]: OS: linux2, 4 cores, ~ 22 GB RAM. Python: 2.7.15
[11:19 PM]: Running 1.8.0
[11:19 PM]: No NCBI SBT file given, will use default, for NCBI submissions pass one here '--sbt'
[11:19 PM]: Previous annotation consists of: 4,803 protein coding gene models and 570 non-coding gene models
[11:19 PM]: Adapter and Quality trimming PE reads with Trimmomatic
[11:26 PM]: Running read normalization with Trinity
[11:38 PM]: Building Hisat2 genome index
[11:38 PM]: Aligning reads to genome using Hisat2
[11:39 PM]: Running genome-guided Trinity, logfile: fastagfftrial3/update_misc/Trinity-gg.log
[11:39 PM]: Clustering of reads from BAM and preparing assembly commands
[11:45 PM]: Assembling 7,189 Trinity clusters using 3 CPUs
[01:12 AM]: 10,311 transcripts derived from Trinity
[01:12 AM]: StringTie installed, running StringTie on Hisat2 coordsorted BAM
[01:13 AM]: Converting transcript alignments to GFF3 format
[01:13 AM]: Converting Trinity transcript alignments to GFF3 format
[01:13 AM]: Running PASA alignment step using 10,311 transcripts
[01:14 AM]: Running PASA annotation comparison step 1
[01:14 AM]: Running PASA annotation comparison step 2
[01:15 AM]: Using Kallisto TPM data to determine which PASA gene models to select at each locus
[01:15 AM]: Building Kallisto index
[01:15 AM]: Mapping reads using pseudoalignment in Kallisto
[01:16 AM]: Parsing Kallisto results. Keeping alt-splicing transcripts if expressed at least 10.0% of highest transcript per locus.
[01:16 AM]: Wrote 4,803 transcripts derived from 4,803 protein coding loci.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/user/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 2243, in main
    alt_transcripts=args.alt_transcripts)
  File "/home/user/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/update.py", line 1074, in GFF2tblCombinedNEW
    genenumber = int(genenumber)
ValueError: invalid literal for int() with base 10: 'CMT646C'
```

Thank you!

**Comment by nextgenusfs** [comment]
Ok... progress at least....  This one is related to the "base" gene name.  More recent NCBI genomes required a underscore in locus_tag names -- so that is what funannotate is looking for.  Let me see if I can find away around this one. 

Side note -- surprising that PASA returned the same number of genes... Would be worth looking at the PASA log files to make sure it looks like it ran correctly.

**Comment by nextgenusfs** [comment]
Okay @viktor-hub -- see if that commit fixes it.  Basically if there is a atypical locus_tag like this genome, it is going to build any new gene models derived from PASA with a slightly different locus tag format as there is no way to programmatically know what the logic was behind these names....
